version: '3.3'

services:
  mongo-login:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/alvaro/mongodata:/data/db
    restart: "no"
    command: [--auth]

volumes:
  mongodata: